title: "Letzter Funke"
subtitle: "Warum wir allein sein könnten und es trotzdem nicht bleiben wollen"
author: "Draven Quantum"
isbn: "" # Add ISBN-13 if applicable
edition: "1"
publisher: "Quantum Horizons" # Example self-publishing imprint
date: "2025"
language: "de"
description: >
  Spekulatives Essayprojekt über die Zukunft der Menschheit, interstellaren Kontakt,
  Zeitreisen, Wurmlöcher und digitales Bewusstsein. "Last Spark" fragt, ob wir entdeckt
  werden, bevor wir verschwinden – und was vom Menschen bleibt, wenn er nicht mehr stirbt,
  sondern über Äonen hinweg existiert.
keywords:
  - Zukunft der Menschheit
  - interstellarer Kontakt
  - Zeitreisen
  - Wurmlöcher
  - digitales Bewusstsein
  - Unsterblichkeit
  - Science-Fiction-Essay
  - transhumanismus
  - außerirdisches Leben
  - Existenzphilosophie
cover_image: "assets/covers/cover.png"
output_formats: ["pdf", "epub", "docx"]
kdp_enabled: false
