title: "Letzter Funke"
subtitle: "Warum wir allein sein könnten und es trotzdem nicht bleiben wollen"
author: "Draven Quantum"
isbn: ""
edition: "1"
publisher: ""
date: "2025"
language: "en"
description: "Spekulatives Essayprojekt über die Zukunft der Menschheit, interstellaren Kontakt, Zeitreisen, Wurmlöcher und digitales Bewusstsein. „Last Spark“ fragt, ob wir entdeckt werden, bevor wir verschwinden – und was vom Menschen bleibt, wenn er nicht mehr stirbt, sondern über Äonen hinweg existiert."
keywords: []
cover_image: "assets/covers/cover.png"
output_formats: ["pdf", "epub", "docx"]
kdp_enabled: false
